/* Generated By:JavaCC: Do not edit this line. SENTENCEConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface SENTENCEConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int COMENTARIO = 4;
  /** RegularExpression Id. */
  int CONTINUE = 5;
  /** RegularExpression Id. */
  int EXIT = 6;
  /** RegularExpression Id. */
  int RETURN = 7;
  /** RegularExpression Id. */
  int WHILE = 8;
  /** RegularExpression Id. */
  int BREAK = 9;
  /** RegularExpression Id. */
  int ELSE = 10;
  /** RegularExpression Id. */
  int NEXT = 11;
  /** RegularExpression Id. */
  int DELETE = 12;
  /** RegularExpression Id. */
  int FOR = 13;
  /** RegularExpression Id. */
  int IF = 14;
  /** RegularExpression Id. */
  int DO = 15;
  /** RegularExpression Id. */
  int IN = 16;
  /** RegularExpression Id. */
  int PRINT = 17;
  /** RegularExpression Id. */
  int GETLINE = 18;
  /** RegularExpression Id. */
  int PADRAO_ID = 19;
  /** RegularExpression Id. */
  int CIFRAO = 20;
  /** RegularExpression Id. */
  int OP_RELACIONAL = 21;
  /** RegularExpression Id. */
  int OP_ATRIBUICAO = 22;
  /** RegularExpression Id. */
  int ABRE_PARENTESES = 23;
  /** RegularExpression Id. */
  int FECHA_PARENTESES = 24;
  /** RegularExpression Id. */
  int FUNCAO_MAT = 25;
  /** RegularExpression Id. */
  int FUNCAO_IO = 26;
  /** RegularExpression Id. */
  int FIM = 27;
  /** RegularExpression Id. */
  int DIGITO = 28;
  /** RegularExpression Id. */
  int LETRA = 29;
  /** RegularExpression Id. */
  int STRING = 30;
  /** RegularExpression Id. */
  int NUMERO = 31;
  /** RegularExpression Id. */
  int LISTA_VAR = 32;
  /** RegularExpression Id. */
  int VAR = 33;
  /** RegularExpression Id. */
  int VAR_ARRAY = 34;
  /** RegularExpression Id. */
  int VAR_BODY = 35;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "<COMENTARIO>",
    "\"continue\"",
    "\"exit\"",
    "\"return\"",
    "\"while\"",
    "\"break\"",
    "\"else\"",
    "\"next\"",
    "\"delete\"",
    "\"for\"",
    "\"if\"",
    "\"do\"",
    "\"in\"",
    "\"print\"",
    "\"getline\"",
    "<PADRAO_ID>",
    "\"$\"",
    "<OP_RELACIONAL>",
    "<OP_ATRIBUICAO>",
    "\"(\"",
    "\")\"",
    "<FUNCAO_MAT>",
    "<FUNCAO_IO>",
    "\";\"",
    "<DIGITO>",
    "<LETRA>",
    "<STRING>",
    "<NUMERO>",
    "<LISTA_VAR>",
    "<VAR>",
    "<VAR_ARRAY>",
    "<VAR_BODY>",
    "\"{\"",
    "\"}\"",
    "\"&&\"",
    "\"||\"",
    "\",\"",
    "\"!\"",
    "\"?\"",
    "\":\"",
    "\"/\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"%\"",
    "\"^\"",
    "\"**\"",
    "\"++\"",
    "\"--\"",
  };

}
