/* Generated By:JavaCC: Do not edit this line. SENTENCETreeConstants.java Version 5.0 */
public interface SENTENCETreeConstants
{
  public int JJTPARSE = 0;
  public int JJTPROGRAMA = 1;
  public int JJTCOMANDOS = 2;
  public int JJTPADRAO = 3;
  public int JJTACAO = 4;
  public int JJTDECLARACAO = 5;
  public int JJTD_EXPRESSAO = 6;
  public int JJTD_FUNCAO = 7;
  public int JJTD_IF = 8;
  public int JJTD_LOOP = 9;
  public int JJTD_CONTROL = 10;
  public int JJTD_LISTA = 11;
  public int JJTEXPRESSAO = 12;
  public int JJTD_FUNCAO_MATEMATICA = 13;
  public int JJTD_FUNCAO_IO = 14;
  public int JJTD_FUNCAO_STRING = 15;
  public int JJTPRINT_LISTA = 16;
  public int JJTEXP_RELACIONAL = 17;
  public int JJTEXP_AND = 18;
  public int JJTEXP_NOT = 19;
  public int JJTEXP_ATRIBUICAO = 20;
  public int JJTEXP_SOMA = 21;
  public int JJTEXP_MULTIPLICACAO = 22;
  public int JJTEXP_POTENCIA = 23;
  public int JJTEXP_NEGACAO = 24;
  public int JJTEXP_INC_DEC = 25;
  public int JJTEXP_SIMPLES = 26;
  public int JJTVAR_STRING = 27;


  public String[] jjtNodeName = {
    "Parse",
    "Programa",
    "Comandos",
    "Padrao",
    "Acao",
    "Declaracao",
    "D_Expressao",
    "D_funcao",
    "D_if",
    "D_loop",
    "D_control",
    "D_lista",
    "Expressao",
    "D_funcao_matematica",
    "D_funcao_io",
    "D_funcao_string",
    "Print_lista",
    "Exp_relacional",
    "Exp_and",
    "Exp_not",
    "Exp_atribuicao",
    "Exp_soma",
    "Exp_multiplicacao",
    "Exp_potencia",
    "Exp_negacao",
    "Exp_inc_dec",
    "Exp_simples",
    "Var_string",
  };
}
/* JavaCC - OriginalChecksum=0701b3dc0bf9173ca75f5bd4ff99025a (do not edit this line) */
